# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm i
    npm run test
  displayName: 'Run tests'
  env:
      APPLITOOLS_API_KEY: $(applitools.api.key)
      APPLITOOLS_BATCH_ID: $(Build.SourceVersion)

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
